### ISSUE TITLE
Httpclient usage

### ISSUE THREAD

**Issue by taooceros** [jjw24/Droplex#1]
Just a small review. Although I don't believe that the download method should be called with large amount.
If you want to reuse the sockethandler, I don't believe that we shall initialize a new one every time requesting an http request, but reuse one socket handler instance. Reusing one httpclient instance will be easier. 

> // HttpClient is intended to be instantiated once per application, rather than per-use. See Remarks.
static readonly HttpClient client = new HttpClient();

**Comment by jjw24** [comment]
resolved in #6
