### ISSUE TITLE
Multithread downloading

### ISSUE THREAD

**Issue by taooceros** [jjw24/Droplex#3]
Is it possible to implement multithread downloading? or utilizing some existing library to do that?

**Comment by jjw24** [comment]
sure if it's needed, but at this stage what scenario would we a multithread download help solve?

**Comment by taooceros** [comment]
I am not sure about that, but seems that multithread downloading can help people in China achieve a potential higher downloading speed. It is quite slow to download python.
![image](https://user-images.githubusercontent.com/45326534/107204707-f3258500-6a37-11eb-8034-6f3aafcef56c.png)

**Comment by taooceros** [comment]
However, I think maybe we can add some mirror to download, like what Dictionary plugins is going to do here.
https://github.com/harrynull/Flow.Launcher.Dictionary/pull/5

**Comment by jjw24** [comment]
sorted in #6 , let's revisit if still a problem
